api_platform:
  title: EcoGarden & co
  description: API pour le projet 12
  version: 1.0.0
  defaults:
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
